#+setupfile: /home/yamagami/org/macros-org/org/org-macros.setup
#           Time-stamp: <2024-02-02 19:35:12 yamagami>
#+title: Ledger-cliによるNPO法人会計注記 -- index
#+date: [ 2024-02-28 ]
#+language: ja
#+link: file file+sys:../static/
#+hugo_base_dir: ~/peace-blog/bingo/
#+hugo_section: posts
#+hugo_tags: ledger-cli NPO 注記
#+hugo_categories: comp
#+options: toc:t
#+draft: false


* NPO注記とは
NPO法人会計では、財務諸表(活動計算書と貸借対照表)の内容を補足するために
**注記** が求められています。その一覧は「こちら」などを参照してください。
# 1. 重要な会計方針
# 2. 会計方針の変更
# 3. 事業費の内訳or事業別損益の状況 （任意）
# 4. 施設の提供等の物的サービス （任意）
# 5. ボランティアによる役務提供の内訳 （任意）
# 6. 使途等が制約された寄付等の内訳 specific-donation-NPO.org
# 7. 固定資産の増減内訳 fixed-assets-rolling-NPO.org
# 8. 借入金の増減内訳
# 9. 役員及びその近親者との取引の内容 related-party-TXN-NPO.org
# 10. その他NPO法人の資産、負債、正味財産の状態等を明らかにするために必要な事項
# (出典）[[https://www.npokaikeikijun.jp/wp-content/uploads/online-seminar3.pdf][オンラインＮＰＯ会計セミナー 第３回 ＮＰＯ法人会計基準 決算編]]


* Index
  
** 使途等が制約された寄付等の内訳
  specific-donation-NPO.org

** 固定資産の増減内訳
  fixed-assets-rolling-NPO.org

** 役員及びその近親者との取引の内容
 related-party-TXN-NPO.org  

* COMMENT 使途等が制約された寄付等の内訳

- 例題は「これ」を参考にしました。
- 寄付、助成金の入金記帳はかんたんでタグづけすればよい
- 経費でも、TXN内でその支出が助成金から出ていることを記録しておくことが必要だろうから、これにもタグづけ
- 問題は ==資産:流動資産:現金預金:使途指定== のようなアカウントを用意しないと注記のときに困るってこと。
- =使途制約:= というタグに、その値として =災害支援= と =教育支援= を与えている。

#+begin_src
(1)  ㈱グッドウイル社から、使途を災害支援に限定した寄付金 5,000,000円がUHF銀行に入金された。
#+end_src
#+begin_example ledger
2024/01/01 ㈱グッドウイル
    ; 使途制約: 災害支援
    経常収益:受取寄付金:使途指定         -5,000,000 JPY
    資産:流動資産:現金預金:使途指定:UFG
#+end_example
- 第2行目の =;= セミコロン以下がタグの設定。
   - =:= コロンの前の =使途制約= がタグ名、その次の =災害支援= がそのタグの値
- 第3行目の =受取寄付金= 科目の下に =使途指定= を設定
- 第4行目の =資産= の =現金預金= 科目の下に =使途指定= 科目、さらにその下に =UHF= と銀行名を設定

#+begin_src
(2)  寄付された金額の内 3,000,000円で被災者の援助物資を購入しストック
#+end_src
#+begin_example ledger
2024/02/01 援助物資のストック
     ; 使途制約: 災害支援
    資産:流動資産:被災者援助物資           3,000,000 JPY
    資産:流動資産:現金預金:使途指定
#+end_example
- 被災者支援物資は =経常費用= のような気もしますが、後日これは被災者に配布するためにストックするので、 =流動資産= 下に =被災者援助物資= としています

#+begin_src
(3) 支援物資をストックから出して被災者に配布
#+end_src
#+begin_example ledger
2024/02/05 援助物資配布
     ; 使途制約: 災害支援
    資産:流動資産:被災者援助物資          -3,000,000 JPY
    経常費用:業務費:その他経費:援助用消耗品費
#+end_example
- 被災者に配布した時点で、資産であった災害援助物資にたいして経常費用として転記
- その際に =援助用消耗品費= にしている（へんだなぁ）

#+begin_src
(4)  グッドウイル社からの要望で、寄付の内 3,000,000円の使途を教育支援に切り替えた
#+end_src

#+begin_example ledger
2024/04/10 災害支援から教育費支援に変更
    資産:流動資産:現金預金:使途指定:UFG   -3,000,000 JPY
    ; 使途制約: 災害支援
    資産:流動資産:現金預金:使途指定:ゆうちょ
   ; 使途制約: 教育支援
#+end_example
- ゆうちょ銀行に預金を移し、使途指定だが教育支援となるような準備をした

* クエリ例
この例では、見やすさのためにクエリの一部だけを表示しているが、実際には
- init-file 指定、Ledgerファイル名指定も行っているが省略している
- Ledgerオプションに =--empty= も使用しているがそれも省略している
#+begin_src
(1)  Ledger元帳データから使途制約タグのあるTXNのbalanceレポートを表示
#+end_src
#+begin_example ledger
$ ledger bal %使途制約 --init-file -f sample-data.leder --empty
      -5,000,000 JPY  経常収益:受取寄付金:使途指定
       2,000,000 JPY  経常費用:業務費:その他経費:援助用消耗品費
       3,000,000 JPY  資産:流動資産
       3,000,000 JPY    現金預金:使途指定
       2,000,000 JPY      UHF
       3,000,000 JPY      ゆうちょ
                   0    被災者援助物資
--------------------
                   0
#+end_example



#+begin_src ledger
$ ledger bal %使途制約=教育
       3,000,000 JPY  資産:流動資産:現金預金:使途指定:ゆうちょ

$ ledger bal %使途=災害
      -5,000,000 JPY  経常収益:受取寄付金:使途指定
       2,000,000 JPY  経常費用:業務費:その他経費:援助用消耗品費
                               0  資産:流動資産
      -3,000,000 JPY    現金預金:使途指定
       2,000,000 JPY      UHF
       3,000,000 JPY    被災者援助物資
--------------------
      -3,000,000 JPY
#+end_src


NPOの注記では、期首残高 当期増加額 当期減少額 期末残高を求めている。
寄付、補助金が年度をまたぐものでなければ、
期首残高はゼロ、期末残高もゼロ、
当期増加額が寄付・補助金の入金額、当期減少額もそれと同額
てのが普通

仮に年度をまたいだとしても、画面のような出力があれば、手入力で表を書くことがかんたん。これをNPOの求めるような表にまとめるのをLedgerにやらせるのは、労多くて益少ない。そもそも、寄付・補助金が何十本もあるようなNPOとか考えられないし（笑）


* COMMENT 固定資産の増減内訳
びっくりしたのは、ソフトウエアが固定資産:無形資産ってこと。減価償却もしろってさ！
- ただし10万未満なら消耗品費だそうだ
会計処理上、金額等の基準により寄付　英語消耗品費として活動計算書に計上するか、固定資産として貸借対照表や財産目録に計上するかのいずれかの処理となります。だって。
　　





* COMMENT NPO2017について
- [[https://www.npokaikeikijun.jp/download/kaisei_balancesheet_201712/][基準新旧対照表]] 大半は役員の報酬に関する追加基準。
関係ありそうなのは、受取寄付金の認識で、

(改正前）受取寄付金は、実際に入金したときに収益として計上する\\
(改正後）受取寄付金は、確実に入金されることが明らかになった場合に収益として計上する

次の一文を財務諸表の注記に付す
#+begin_example
財務諸表の作成は、ＮＰＯ法人会計基準（2010年７月20日　2017年12月12日最終改正　ＮＰＯ法人会計基準協議会）によっています。
#+end_example




# Local Variables:
# eval: (org-hugo-auto-export-mode)
# End:
