#+setupfile: /home/yamagami/org/macros-org/org/org-macros.setup
#           Time-stamp: <2023-12-26 13:52:20 yamagami>
#+title: Adding Google Analyitcs4 to My Site
#+date: [2023-12-26]
#+language: ja
#+link: file file+sys:../static/
#+hugo_base_dir: ~/peace-blog/bingo/
#+hugo_section: posts
#+hugo_tags: test
#+hugo_categories: comp

#+options: toc:nil
#+draft: false


このサイト（ **Yam's Peace Blog** ）は
#+begin_example
Emacs/Hugo/GitHub/Netlify
#+end_example
という流れで公開しています。

2023年前半まではGoogle Universal Analytics（ **UA** ）でアクセス状況をモニターしていました。

**UA** は2023/07/01で終了したのですが、
新しいバージョンのアナリティクス＝Google Analytics4( **GA4** )へ移行するのをダラダラと先延ばししていました。

年末も押し迫った2023年12月下旬になってようやく **GA4** への移行に着手しました。
移行のための情報をネット上の日本語サイトでいろいろ探索しましたが、
いずれも「帯に短したすきに長し」、というかHugoベースのサイトの **GA4化** にとっては無用な情報が多くてほとんど「たすきに長し」でした。

しかし Rodney Maiatoさんの分かりやすいサイト（
[[https://rodneymaiato.dev/posts/how-to-add-google-analytics-to-a-hugo-site/][How to Add Google Analytics to a Hugo Site）]]に出会ったおかげで、記事に書かれている通り 5分程度の作業で移行が終わりました。
ほんとうに助かりました。ありがとうございました。

* 手順
上のサイトに紹介されている通りに作業（というほどでもありません:sweat:）
1. =./config.toml= に次の行を追記
     #+begin_src
      google_Analytics = "G-XXXXXXXX"
     #+end_src
2. =./layout/partial/head.html= の次行を確認
   #+begin_src
   {{ template "_internal/google_analytics.html" }}}
   #+end_src

3. 上の修正を保存
4. Netlifyにデプロイ
5. 1日から2日ほど待つとGoogle Analytisでアクセス情報を見ることができる

これだけです。Hugoはほんとうにすばらしい！


# Local Variables:
# eval: (org-hugo-auto-export-mode)
# End:
