#+setupfile: /home/yamagami/org/macros-org/org/org-macros.setup
#           Time-stamp: <2021-05-14 19:06:30 yamagami>
#+title: フデリンドウ
#+date: [ 2021-05-20 ]
#+language: ja
#+link: file file+sys:../static/

#+hugo_base_dir: ~/peace-blog/bingo/
#+hugo_section: posts
#+hugo_tags: 自然誌
#+hugo_categories: comp

#+options: toc:1
#+draft: false

* フデリンドウ
とは？
- 日本全国 標高1,800m までの広範囲に生息
- しかし徐々に減少
- 新治市民の森にもあるようだ。群落も

* はたけの妖精
2016年5月に畑の脇にはじめてフデリンドウが1輪だけ咲いた。
畑脇の30センチほどの低い土手（西側）に
（写真?）

2018年5月には同じ場所で10株にも増殖
facebook にアップ

2020年にも同じ場所で同じ規模で咲いた
facebookにアップ


* しかし
 
しかし、2021年5月には5月10日まで待ったけれども、同じ場所には1株も1輪も咲かない！

一体どうしたことか。フデリンドウが咲く場所には足を踏み入れないようにまた草刈り機での草刈りもしないように、夏から秋にかけて最新の注意を払っていた

気候変動なのか？2年草とは？


ところが、今までとは全然べつの場所＝同じ畑の土手の反対側（東側）の底部あたりに、2株！　

どうやってこの距離を移動したのか？ほんとうに不思議。

けど、5月初旬の畑仕事の合間に見てはニヤニヤしていたのが、一度は絶望した
再発見したときには、おもわず妻を呼びに帰った

妻もえっーっと言いながら、サンダルばきで小走り

見て、ほんとうに嬉しそうにしていた。

小さな小さな草なのに、気持ちをやわらかにしてくれる
根が薬になるというが、花も向精神薬だわ


* Acknowledgement
- 野島大志, 中井静子, 横山潤 (2011).   [[https://yamagata.repo.nii.ac.jp/?action=repository_uri&item_id=3247&file_id=17&file_no=1][ 分子同定に基づくフデリンドウと菌根菌の対応関係の解析]] 山形大学理学部裏磐梯湖沼実験所報, 18, 42-42.

- 矢沢静江, 小池保次, 高島文三 (1994). [[https://twcu.repo.nii.ac.jp/?action=repository_uri&item_id=23642&file_id=22&file_no=1][ 東京女子大学キャンパスの植物]] Science reports of Tokyo Woman's Christian University 44(3), 1239-1272.

- 越尾淑子, 原田真知子 (1994). [[https://tokyo-kasei.repo.nii.ac.jp/?action=repository_uri&item_id=10541&file_id=22&file_no=1][東京家政大学構内の野草について]] 東京家政大学研究紀要　第34集,（2），p.33～39.

- 冨永達, 馬場多久男, 川越久史, 渡辺 直子 (2007).  [[https://soar-ir.repo.nii.ac.jp/record/10622/files/v30n01_07.pdf][信州大学農学部野辺山キャンパス植物目録]] 信州大学農学部紀要, 30-1, p.41-54.



* COMMENT memo
野島他 2011
混合栄養性で あ る と 考え
られる ァヂリ ン ド ウ Gentiana zollinge討 を 対象 にp 分子 同
定 に基づい て 菌根菌相を明 ら か に し た@ ま たp 得られた結
果を既に報告 さ れ て い る リ ン ド ウ 科植物の菌根菌相 と 比較
し た@ 東日本の 8 ヶ 所か らァヂリ ン ド ウ を探集 し 1 8srDNA
の 部分櫨基配列 に基づ い て 菌根菌を 同定 し た と こ ろ ， いず
れ も Glomus group A に属す る 広範囲 のアー パ λ キ 品 ラ ー菌
根菌が得 ら れた. し か しその中でも Glomus aureum お よ び
リ ン ド ウ 科菌寄生植物 防')'ria の 菌根菌 と 単系統に な る 菌が
多 く 得られ， ア ー パ ス キ 旦 ラ ー菌根菌に対す る あ る 程度 の
選好性を示す こ と が 明らかと なった@


  矢沢(1994)
寮の先生方のお蔭で,寮の近くにヒトリシズカやニリンソウ・ヤマブキソウなどの群落があり,また,東校舎の北側の大木の下にはギンランの群落が見られる。一方,近年になって,キンラン・サイハイラン・ジュウニヒトエ・フデリンドウなどは姿を消しかかってきている。キャンパスの植生の今後の課題としては,除草剤散布・大気汚染・人手不足・建築計画等の影響から,長期間かかってつくられた生態系をできるだけ保全し,大切な種を保護して,キャンパスの自然を調和のとれたものとして存続させて行くための方策を立てて,実行することが大切な事だと思う。


# Local Variables:
# eval: (org-hugo-auto-export-mode)
# End:
