#+title: さようならWordPress
#+date: 2021-03-26
#+link: file file+sys:../static/

#+hugo_base_dir: ~/peace-blog/bingo/
#+hugo_section: posts
#+hugo_tags: Emacs hugo ox-hugo Netlify GitHub
#+hugo_categories: comp

#+hugo_custom_front_matter: :toc true
#+draft: false

これまで2年ほどブログ書きは下のようなフローでやってきました[fn:long-time-ago]。
#+begin_example
Emacs > org2blog > WordPress > freenom > AWS
#+end_example
しかし
1) WordPress(WP)ではバージョンアップに追いつくのが大変
2) サボっていると、画像ファイルが表示されないなどの *トラブル* が頻発
3) トラブルがあっても自力で十分に対応できません（非力のため）
5) SSL対応もしなくちゃならないし・・・
6) AWSも最初の1年間はほぼ無料でありがたかったけど、その後は年間120ドルほどになって結構 *負担* が大きい

などなどから一念発起。この際、ブログ書きの流れをつぎのように変えようと思いました。
#+begin_example
Emacs > org-mode > ox-hugo > Hugo > Netlify > GitHub 
#+end_example

ところが始めてみるとあちこちに地雷や落とし穴が！ 
ちゃんとした「新装開店」まで　まだ一山も二山もあるかと思います。
* 四苦八苦ログ
** 最大の難関
NetlifyがGitHubレポジトリをデプロイするところでかなりはまりました。
ウエッブで調べてみると、とても簡単だったという記事がある一方で、
ひどくハマったという記事が英語でも日本語でも多数あります。
それらを見ながらほんとうにいろいろやりました。

文字通り四苦八苦しましたが、ついに *2021/03/25* に初デプロイ成功！。
うまくいった理由は
1) hugoを =hugo_extended_0.81.0_Linux-64bit.deb= にアップしたこと
2) Netlifyウエブサイトの'Deploy settings'中の'Build settings'の内容をGitHubのサイトルートにしたこと
    #+begin_example
Base = bingo/
　：
Publish = public
　：
    #+end_example
などが奏功したのではないかと思いますが、じつは理由はよく分かっていません。

何回もやりなおして苦労したので、後日 *org-mode＋~ox-hugo＋Hugo+Netlify＋GitHub* でホームページを公開する手順を整理して備忘録としてまとめようと思います。

** Hugoテーマの変更
ここでもハマりました。つまらないことですがテーマによって必要なディレクトリの名称が
postsだったりpostだったり！それ以外にもテーマを変更したときに変更の必要な設定ファイル類があちこちに在ります。分かるまでエラーの嵐でした。

まったく新規にレポジトリを作ってテーマの設定をまっさらな状態で行えばスムーズなのでしょうが、そうるすとNetlifyのデプロイをやり直さなければなりません。そこでまたハマる。

それから、いったんローカルのある特定のディレクトリでhugo初期化した投稿記事原稿には、環境が変わると変更が必要になるところがあります[fn:2]。40から50本程度の記事数ですが、手作業ではできないのでその都度スクリプトを書いたりして、結構つかれました[fn:escape]。

あとヘッダー内の *ARCHIVES* という語を *POSTS* に変更したくて、コード内を ~grep -ir~ したのですが見つからず困ってました。そしたら灯台下暗し、 ~config.toml~ 内で簡単に書き換えできました。

** Netlifyのドメイン名変更
ここはまだハマった状態です（笑）。
   
* 環境
ソフトウエアの環境は次のとおりです。
|----------+-----------------|
|          |             <r> |
| Software |         Version |
|----------+-----------------|
| OS       |     Ubuntu20.04 |
| Emacs    |            26.3 |
| org-mode |           9.4.4 |
| ox-hugo  |             0.7 |
| hugo     | extended 0.81.0 |
| git      |          2.25.1 |
|----------+-----------------|

（これはテストページです）

* Footnote
[fn:long-time-ago] 今は昔、HTML＝ホームページの黎明期、国内の大学で学科単位のHPを持っているところがほとんどなかった頃、HTMLの直書きで所属学科のHPを一人で書きました。その時の記憶が少しだけ残っていて今回の作業にもいくらか役に立ちました。

[fn:2] ~#+HUGO_BASE_DIR:~ の変更は必須です。もしこれが記事中に散在する「一般語」と重複すると置換作業が面倒だったのですが、幸い今回は重複ゼロでしたので簡単なスクリプトで一発置換できました。

[fn:escape] これを回避する方法があるようです。
# Local Variables:
# eval: (org-hugo-auto-export-mode)
# End:
