#+setupfile: /home/yamagami/org/macros-org/org/org-macros.setup
#           Time-stamp: <2024-01-23 17:42:46 yamagami>
#+title: 小規模学会のためのLedgeｒポスティング例 --- NPO法人会計基準に準拠しながら
#+date: [2024-01-24]
#+language: ja
#+link: file file+sys:../static/
#+hugo_base_dir: ~/peace-blog/bingo/
#+hugo_section: posts
#+hugo_tags: Ledger-cli NPO 会計
#+hugo_categories: comp
#+options: toc:t
#+draft: false

* イントロダクション
ここでは
#+begin_example
会員数1,000名未満の小規模な学会が
Ledger-cliを使ってNPO法人会計基準にそって会計処理する際の
具体的なポスティング例を紹介します
#+end_example
NPO法人会計の体系的な説明や勘定科目構造などについてはネット上に良い資料がたくさんありますので、そちらを参照してください[^footnote_whats_npo]。

NPO法人会計の財務諸表をLedgerで書く方法は
「[[https://bred-in-bingo.netlify.app/posts/financial-statements-for-NPO/][NPO法人会計に準拠した財務諸表をLedger-cliで書く]]」をみてください。


[^footnote_whats_npo]: 「[[https://www.npokaikeikijun.jp/wp-content/uploads/handbook201202.pdf][NPO 法人会計基準ハンドブック]]」、「[[https://www.ssdesign.co.jp/kaiN/kaiN_shiwake.pdf][「ＮＰＯ法人会計」の仕訳]] 」などたくさんあります。

* この記事について
- 小規模学会の経理を例として使っていますが、一般的なNPO法人会計への適用にもいくらか役立つと思いますが、
- 目に付いたトランザクションをどうポスティングするかのメモを寄せ集めたものです。体系的な説明にはなっていません
- 少しずつポスティング例を増やして行く中で、徐々に体系化できればと思っています

**  トップレベルの４勘定科目
NPO法人会計で使われる日本語の勘定科目名の内、最上位の4科目は
図[[top-level-accounts]] のとおりです。

#+name: top-level-accounts
#+attr_html: :width 45%
#+caption: 勘定科目ツリーのトップレベル４勘定科目
[[file:top_level-AC.svg]]

** 上の4勘定科目に属するサブ科目構造
この記事内のポスティング例の中で使っているサブ科目の構造を紹介しておきます。
*** 経常経費（Expenses）
# NPO法人の場合には =Expenses= は
# 「事業費」direct cost(expenditure)と「管理費」overheads に大別されます。
#+attr_html: :width 45%
#+caption: 経常経費科目下のサブ勘定科目
[[file:cutdown-expenses-tree.svg]]

*** 経常収益(Income)
#+name: income_tree   
#+attr_html: :width 53%
#+caption: 経常収益科目下のサブ勘定科目
[[file:cutdown-income-tree.svg]]

*** 資産（Assets）
#+name: assets_tree
#+attr_html: :width 45%
#+caption: 資産科目下のサブ勘定科目
[[file:cutdown-assets-tree.svg]]

*** 負債(Liabilities)
#+name: liab_tree
#+attr_html: :width 45%
#+caption: 負債科目下のサブ勘定科目
[[file:cutdown-liab-tree.svg]]

* ポスティング サンプル

** 入会金と年会費の例
(1) 2021/04/10に東京太郎氏が正会員の入会金と年会費を「ゆうちょ」に振り込んだ。\\
東京太郎氏の会員番号（ID）は20220405。「ゆうちょ」は後述するエリアスでLedgerによって =Assetes:流動資産:現金預金:ゆうちょ= に展開されます。
#+BEGIN_EXAMPLE
2021/04/05 東京太郎
    ; ID: TT-20210405
    経常収益:受取入会金:正会員:2021           -10,000 JPY
    ゆうちょ     　　                       10,000 JPY 

2021/04/10 東京太郎
    ; ID: TT-202104105
    経常収益:受取会費:正会員:2021             -6,000 JPY
    ゆうちょ　　　                           6,000 JPY
#+end_example

(xx) 2021/04/15に サポーター株式会社から賛助会員の年会費が振り込まれた
#+BEGIN_EXAMPLE
2021/04/14 サポーター株式会社
    経常収益:受取会費:賛助会員:2021               -50,000 JPY
    資産:流動資産:現金預金:UFJ
#+end_example

(2) 2021/03/15に大阪花子氏が2022年（翌年度）の会費を「UFJ銀行」に前払いした。
#+BEGIN_EXAMPLE
2021/03/15=2022/04/01 大阪花子
    ; 前受会費
    ; ID:20100515
    経常収益:受取会費:正会員:2022            -6,000 JPY
    資産:流動資産:現金預金:UFJ            6,000 JPY
  #+END_EXAMPLE
=経常収益= アカウント内の最下位の科目を会費の年度としてあります。ここが =2022= になっていますので、あえて =前受け会費= を勘定科目化する必要はありません。
  
** 受取補助金の例
(3) 文科省から補助金が「ゆうちょ」に振り込まれた。
  #+BEGIN_EXAMPLE
2021/10/01 文部科学省
    経常収益:受取補助金:公開講演会補助金     -1,100,000 JPY
    ゆうちょ                              1,100,000 JPY
  #+END_EXAMPLE

** 事業収入の例
(4) 会誌の定期購読料が「XYZ大学図書館」から =UFJ= に振り込まれた。\\
この例では =UFJ= は[[#ledgerrc]]で =資産:流動資産:現金預金:UFJ= とエリアス定義されています。エリアス定義の説明が必要。。。。。。。。
  #+BEGIN_EXAMPLE
2022/01/31 XYZ大学図書館
    経常収益:事業収入:定期購読                -5,000 JPY
    UFJ
#+end_example
また第2行目のトランザクションの金額 =5,000 JPY= が省略されています。Ledgerでは1つのポスティング内のトランザクションは **1つだけ** 金額を省略できます[^footnote_zerosum]。


[^footnote_zerosum]: ポスティング内の全トランザクションの合計は必ずゼロになりますので、省略された金額はLedgerが補完してくれます。


(5) 「(一社)学術著作権協会」から著作物使用料金が「ゆうちょ」に振り込まれた。\\
=yucho= もエリアスで、Ledger内部で =Assetes:流動資産:現金預金:ゆうちょ= に展開されます。
#+begin_example
2023/03/27 (一社)学術著作権協会
    経常収益:事業収入:著作物使用料金          -24,529 JPY
    yucho
#+end_example
(6) 2022/07/28に京都次郎氏から会誌の「著者負担金」が振り込まれた。
#+begin_example
2022/07/28 京都次郎
          ; ID: 19920601
          経常収益:事業収入:著者負担金          -50,000 JPY
          UFJ
#+end_example

(7) 名古屋良子氏から「別刷り代金」が「SMBC」に振り込まれた。
#+begin_example
2022/07/29 名古屋良子
          ; ID:  20150810
          経常収益:事業収入:別刷代               -3,000 JPY
          UFJ
  #+END_EXAMPLE


** Expenses(経常経費）の例
(xx) 会誌印刷費を「世界印刷」に振り込んだ。
#+BEGIN_EXAMPLE
2021/10/15 ㈱世界印刷
    経常費用:事業費:会誌印刷費     340,000 JPY
    ゆうちょ
#+end_example

(8) 学術大会の講師謝金を新宿花子氏の「ゆうちょ」口座に振り込んだ。この例では簡単のために源泉税は転記していません（[[#genseizei][後述します]]）。
#+BEGIN_EXAMPLE
2022/12/15 新宿花子
    経常費用:事業費:講師謝金             32,000 JPY
    経常費用:管理費:振込手数料              165 JPY
    yucho                  (-32,00 JPY - 165 JPY )
#+END_EXAMPLE

(xx) ㈱業務委託社に業務委託費を振込
#+BEGIN_EXAMPLE
2022/06/30  ㈱業務委託社
    経常費用:管理費:業務委託費       450,000 JPY
    ゆうちょ
#+END_EXAMPLE

(9) ㈱業務委託社に理事会の会議費費用を振り込んだ。
#+BEGIN_EXAMPLE
2022/07/27 ㈱業務委託社
    経常費用:管理費:会議費:理事会             2,520 JPY
    ゆうちょ                                -2,520 JPY
#+END_EXAMPLE

** 源泉税の例
:properties:
:custom_id: genseizei
:end:

(10) 大会シンポジストの静岡三郎氏に源泉税を天引した交通費を振り込んだ。\\
=ゆうちょ= はエリアスで =資産:流動資産:現金預金:ゆうちょ= に展開されます。
#+BEGIN_EXAMPLE
2022/12/15 静岡三郎
    ; 大会シンポジストに交通費振込
    経常費用:事業費:交通費      ( 30,000 JPY - (floor( 30,000 JPY * 0.1021 ))
    経常費用:事業費:租税公課:源泉税            (floor( 30,000 JPY * 0.1021 ))
    ;;経常費用:管理費:振込手数料                      165 JPY
    負債:未払源泉税                          (floor( -30,000 JPY * 0.1021 ))
    ゆうちょ
#+end_example
ここで関数 =floor= は小数点以下切捨て。四捨五入は =round= 、切り上げは =ceiling= です。

(11) 静岡三郎氏の源泉税を「UFJ」銀行から「XYZ税務署」に振込。
#+BEGIN_EXAMPLE
2022/12/25 XYZ税務署
    ; 静岡三郎氏の源泉税納付
    負債:未払源泉税           (floor( 30,000 JPY * 0.1021 ))
    UFJ
#+END_EXAMPLE
=UFJ= もエリアス。 =資産:流動資産:現金預金:UFJ= に展開されます。



** 立替金の例
立替金は =資産:立替金= に収納します。

(12) 相模原花子氏が支払った立替金を後日、学会の「ゆうちょ」から振り込んだ。
#+BEGIN_EXAMPLE
2022/02/28 相模原花子
    ; 会議用Zoom使用料金（立替）
    経常費用:事業費:通信費郵便費               2,200 JPY
    資産:立替金:H.Sagamihara               -2,200 JPY

2022/03/30 相模原花子
    資産:立替金:H.Sagamihara                 2,200 JPY
    yucho                                     -2,200 JPY
#+END_EXAMPLE

** 未払金の例
(13) 年度末日において、業務委託先に通信郵便費の未払い金がある場合のポスティング
#+BEGIN_EXAMPLE
2022/03/31 ㈱事務代行社
 　 経常費用:管理費:通信郵便費          55,232 JPY 
    負債:未払金:㈱事務代行社    -55,232 JPY  
#+END_EXAMPLE

** 仮受金の例
(14) 2019/07/01にナゾの振込が「ナゾフリコミ」さんから7,000円あった。調査不能のために当面、毎年度、期首振替する。
#+BEGIN_EXAMPLE
2019/07/01=2022/04/01 ナゾノフリコミ
    ; 振込元について調査不能。毎年度期首振替
    負債:仮受金                         -7,000 JPY
    資産:流動資産:現金預金:ゆうちょ              7,000 JPY
#+END_EXAMPLE

(15) 振込元が判明し返金する時のポスティング。負債:仮受金に収納する。
#+BEGIN_EXAMPLE
2023/10/10 ナゾノフリコミ
    負債:仮受金               7,000 JPY
    ゆうちょ                        -7,000 JPY
#+END_EXAMPLE


* （参考資料1） Ledger-cliの設定ファイル

** ~/.ledgerrc
   :PROPERTIES:
   :CUSTOM_ID: ledgerrc
   :END:
=.ledgerrc= は、
Ledger-cliのもっとも基本的な環境を設定するためのファイル。
Ledger-cliをインストールするとユーザのホームホーム ディレクトリに作成されます。このデフォルトの場所やファイル名を変更するには、
`$ ledger --init-file 'PATH/init-file.dat'`します。くわしくはマニュアルを参照してください。

- [[https://github.com/yradunchev/ledger/blob/master/.ledgerrc]]

** 内容例
#+BEGIN_EXAMPLE
;;--file 
--color
--check-payees
--date-format %Y/%m/%d
--pager /usr/bin/less
--sort date
;;--pedantic
;;--explicit
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;  Aliases
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
alias income=Income
alias expns=Expenses
alias assets=Assets
alias yucho=資産:流動資産:現金預金:ゆうちょ
alias ゆうちょ=資産:流動資産:現金預金:ゆうちょ
alias UFJ=資産:流動資産:現金預金:UFJ
　　：
＜これにならって好きなだけエリアスを追加できます＞
#+END_EXAMPLE

# 第2回以降のデプロイで追加する  2024/01/14 20:26:45
# include文の書き方も交えて
#
# payees.dat, accounts.dat tags.dat
# #+BEGIN_EXAMPLE
#     include ~/local-ledger-directory/configs/accounts.dat
#     include ~/local-ledger-directory/configs/payees.dat
#     include ~/local-ledger-directory/configs/tags.dat
# #+END_EXAMPLE


* （参考資料2） 活動報告書、貸借対照表

  
* Footnotes:

# Local Variables:
# eval: (org-hugo-auto-export-mode)
# End:
